Document: passenger
Title: Debian passenger Manual
Author: <insert document author here>
Abstract: This manual describes what passenger is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/passenger/passenger.sgml.gz

Format: postscript
Files: /usr/share/doc/passenger/passenger.ps.gz

Format: text
Files: /usr/share/doc/passenger/passenger.text.gz

Format: HTML
Index: /usr/share/doc/passenger/html/index.html
Files: /usr/share/doc/passenger/html/*.html
